In [1]:
import argparse

In [2]:
%run model.ipynb

/Users/britnybrito/opt/anaconda3/lib/python3.9/site-packages/torch/amp/autocast_mode.py:204: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')


aaaaaa QT
196
torch.Size([10, 300, 196])
torch.Size([10, 301, 196])
torch.Size([1, 301, 196])
torch.Size([10, 50])
aaaaaa QT
196
torch.Size([10, 108, 196])
torch.Size([10, 109, 196])
torch.Size([1, 109, 196])
torch.Size([10, 527])


In [3]:
%run dataloader.ipynb
import csv

In [4]:
labels = 'class_labels_indices.csv'
audio_conf = {'num_mel_bins': 128, 'target_length': 1024, 'freqm': 24, 'timem': 192, 'mixup': 0.5}
ayuda = AudiosetDataset('test_data.json', audio_conf, label_csv = labels)

number of classes is 201


In [5]:
train_loader = torch.utils.data.DataLoader(ayuda)





In [6]:
ast_mdl = ASTModel( class_n=75)

aaaaaa QT
196


In [7]:
import sys
import os
import datetime
sys.path.append(os.path.dirname(os.path.dirname(sys.path[0])))
import time
import torch
from torch import nn
import numpy as np
import pickle
from torch.cuda.amp import autocast,GradScaler

In [8]:
for i in ayuda:
    print(i)

(tensor([[-15.9424, -15.9424, -15.9424,  ..., -15.9424, -15.9424, -15.9424],
        [-15.9424, -15.9424, -15.9424,  ..., -15.9424, -15.9424, -15.9424],
        [-15.9424, -15.9424, -15.9424,  ..., -15.9424, -15.9424, -15.9424],
        ...,
        [ -1.0959,  -2.9812,   0.4622,  ...,   0.1087,   0.0980,   0.8148],
        [ -1.6430,  -3.0943,   0.3491,  ...,  -0.1712,  -0.7052,  -0.4631],
        [ -1.3154,  -3.0489,   0.3945,  ...,  -0.1995,  -0.6353,  -1.1549]]), tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

(tensor([[-13.9962, -15.9424, -13.6367,  ..., -14.9121, -14.0861, -14.3319],
        [-13.9441, -15.3573, -11.9139,  ..., -11.3308, -12.6276, -12.3412],
        [-12.1464, -15.9424, -13.2326,  ..., -10.0874, -11.3618, -12.3234],
        ...,
        [ -6.3284,  -8.2486,  -4.8052,  ...,  -6.9081,  -7.2950,  -8.6544],
        [ -6.3268,  -8.1609,  -4.7175,  ...,  -7.0808,  -8.2401,  -8.0163],
        [ -5.9645,  -8.1492,  -4.7058,  ...,  -9.0746,  -8.8596,  -7.9588]]), tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

(tensor([[-15.9362, -15.9424, -14.4831,  ..., -12.5071, -12.3034, -12.0384],
        [-14.0026, -15.9424, -13.1954,  ..., -12.7171, -12.5355, -13.0677],
        [-13.3494, -15.9424, -12.8965,  ..., -13.1600, -12.9849, -14.0767],
        ...,
        [ -1.2095,  -4.2095,  -0.7661,  ...,   4.8844,   3.1261,   2.1540],
        [ -4.3279,  -5.8791,  -2.4357,  ...,   3.9767,   3.7926,   1.5230],
        [ -1.2480,  -4.0480,  -0.6046,  ...,   2.9277,   3.2426,   2.8498]]), tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

(tensor([[-15.9424, -15.9424, -15.9424,  ..., -15.9424, -15.9424, -15.9424],
        [-15.9424, -15.9424, -15.9424,  ..., -15.9424, -15.9424, -15.9424],
        [-15.9424, -15.9424, -15.9424,  ..., -15.9424, -15.9424, -15.9424],
        ...,
        [  2.1637,  -0.8892,   2.5542,  ...,   0.3208,   0.0681,  -2.1667],
        [  1.9578,  -1.0421,   2.4013,  ...,   1.7121,  -1.0268,  -1.7245],
        [  0.7653,  -2.6382,   0.8052,  ...,   1.1569,  -1.3701,  -2.1206]]), tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

(tensor([[-15.9424, -15.9424, -15.9424,  ..., -15.9424, -15.9424, -15.9424],
        [-15.9424, -15.9424, -15.9424,  ..., -15.9424, -15.9424, -15.9424],
        [-15.9424, -15.9424, -15.9424,  ..., -15.9424, -15.9424, -15.9424],
        ...,
        [ -8.3236, -12.0745,  -8.6311,  ...,  -4.6861,  -5.4123,  -5.4763],
        [ -4.9753,  -8.5179,  -5.0745,  ...,   2.0167,   0.4312,   0.1820],
        [ -6.3798,  -6.4452,  -3.0018,  ...,   2.1405,   2.2774,   2.0487]]), tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

(tensor([[-15.9424, -15.9424, -15.9424,  ..., -15.9424, -15.9424, -15.9424],
        [-15.9424, -15.9424, -15.9424,  ..., -15.9424, -15.9424, -15.9424],
        [-15.9424, -15.9424, -15.9424,  ..., -15.9424, -15.9424, -15.9424],
        ...,
        [ -2.8034,  -5.5741,  -2.1307,  ...,  -3.9353,  -3.5645,  -2.0595],
        [ -2.7838,  -5.4971,  -2.0537,  ...,  -4.1299,  -4.7144,  -4.0949],
        [ -2.6030,  -5.4336,  -1.9902,  ...,  -4.7246,  -3.6315,  -3.0672]]), tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

KeyboardInterrupt: 

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
for i, (audio_input, labels) in enumerate(train_loader):
    audio_input = audio_input.to(device, non_blocking=True)
    with autocast():
        audio_output = ast_mdl(audio_input)
                

/Users/britnybrito/opt/anaconda3/lib/python3.9/site-packages/torch/amp/autocast_mode.py:204: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')


torch.Size([1, 1212, 196])
torch.Size([1, 1213, 196])
torch.Size([1, 1213, 196])
torch.Size([1, 1212, 196])
torch.Size([1, 1213, 196])
torch.Size([1, 1213, 196])
torch.Size([1, 1212, 196])
torch.Size([1, 1213, 196])
torch.Size([1, 1213, 196])
torch.Size([1, 1212, 196])
torch.Size([1, 1213, 196])
torch.Size([1, 1213, 196])


In [ ]:
ast_mdl(ayuda
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")